### ISSUE TITLE
Custom dns policy makes sdp-dnsmasq crash

### ISSUE THREAD

**Issue by thomascellerier** [appgate/sdp-k8s-client#38]
Given a pod with the following spec:
```yaml
     dnsConfig:
       nameservers:
       - 10.97.2.20
       - 10.97.2.23
     dnsPolicy: None
```

Results in the sdp-dnsmasq sidecar failing to start:
```
Unable to get the kube dns service!. Dying now!
```

We should at least detect the issue and emit a relevant error.

**Comment by lepiolet** [comment]
Right now we detect it but the error is really far from relevant :D

Since we don't support that option (I don't really know if there is a user case for it) we can just let the injector to fail the validation of the POD in that case.

**Comment by thomascellerier** [comment]
Yes let's just make it clear the `dnsPolicy: None` is not supported right now.
We should be explicit about which `dnsPolicy` we support.

**Comment by anoncam** [comment]
what does your `Corefile` look like?

**Comment by anoncam** [comment]
> 

Have you tried adding something like:

```yaml
spec:
  hostname: 
  subdomain: 
  containers:
  - image: # image ref
    name: sdp # name reference to corresponding service `metadata.name`
---
# associated service
apiVersion: v1
kind: Service
metadata:
  name: sdp # or something similar
spec:
  selector:
    name: sdp
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
```



using approach outlined [here](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/)
